plot(a,k3,'-o','MarkerIndices',1:1:length(a));
xlim([0 1])
xlabel('a','FontSize',12)
ylabel('Power (%)','FontSize',12)
title('Power-a plot for dependent process generated by AR processes','FontSize',12)
grid on
hold on 
plot(a,k5,'-o','MarkerIndices',1:1:length(a));
hold on 
plot(a,k7,'-o','MarkerIndices',1:1:length(a));
hold on 
plot(a,k9,'-o','MarkerIndices',1:1:length(a));
hold on 
plot(a,k20,'-o','MarkerIndices',1:1:length(a));
hold on 
plot(a,k30,'-o','MarkerIndices',1:1:length(a));
legend({'K=3','K=5','K=7','K=9','K=20','K=30'},'FontSize',12,'Location','southeast')
hold off